# Generated by Django 5.2.3 on 2025-06-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('combustible', models.CharField(max_length=30)),
                ('transmision', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=50)),
                ('puertas', models.PositiveSmallIntegerField()),
                ('categoria', models.CharField(choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('van', 'Van'), ('otro', 'Otro')], max_length=20)),
                ('potencia', models.CharField(max_length=30)),
                ('valvulas', models.CharField(max_length=30)),
                ('control_traccion', models.BooleanField(default=False)),
                ('seguridad', models.TextField()),
                ('confort', models.TextField()),
            ],
        ),
    ]
