# Generated by Django 5.2.3 on 2025-06-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='confort',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='control_traccion',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='seguridad',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='abs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='airbags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='aire_acondicionado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='alimentacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='alto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ancho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='arbol_levas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='bloqueo_central',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='bluetooth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_tanque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cilindraje',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cinturones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='frenos_delanteros',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='frenos_traseros',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='largo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='potencia_hp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='radio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='suspension_delantera',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='suspension_trasera',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='torque',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='traccion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='usb',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vidrios_electricos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='volumen_baul',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='puertas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='valvulas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
