# Generated by Django 4.2.7 on 2025-06-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_color_remove_vehiculo_confort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
