# Generated by Django 5.2.3 on 2025-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_vehiculo_airbags_alter_vehiculo_alimentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen_archivo',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
