# Generated by Django 5.2.3 on 2025-06-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_mayor', 'Admin Mayor'), ('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('usuario', 'Usuario común')], default='usuario', max_length=20),
        ),
    ]
