# Generated by Django 5.2.3 on 2025-06-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_acepta_politica_usuario_acepta_terminos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
