# Generated by Django 5.2.3 on 2025-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='persona_natural',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
