# Generated by Django 5.2.3 on 2025-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_persona_natural'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiene_experiencia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiene_licencia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
